2019-11-16 15:33:29,905 [MainThread:156568] [G:/pythonProject/Django/myWX_l_ningmo/myGlobalConfig/tests.py:logger_demo:11] [INFO]- hello world
2019-11-16 15:33:29,905 [MainThread:156568] [G:/pythonProject/Django/myWX_l_ningmo/myGlobalConfig/tests.py:logger_demo:12] [INFO]- hello world [FILTER FLAG]
2019-11-16 15:33:29,906 [MainThread:156568] [G:/pythonProject/Django/myWX_l_ningmo/myGlobalConfig/tests.py:logger_demo:14] [DEBUG]- debug message
2019-11-16 15:33:29,906 [MainThread:156568] [G:/pythonProject/Django/myWX_l_ningmo/myGlobalConfig/tests.py:logger_demo:16] [ERROR]- error message
2019-11-16 16:08:12,647 [Dummy-1:195536] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 16:08:12,648 [Dummy-1:195536] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 16:08:12,650 [Dummy-1:195536] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 16:08:12,655 [Dummy-1:195536] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 16:08:55,548 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 16:08:57,240 [Thread-2:196180] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 16:08:57,258 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 16:08:57,258 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 16:08:57,259 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 16:08:57,261 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'oq6riptmjh0jwn6g6crryvq9pwvhffv6'  LIMIT 1; args=('oq6riptmjh0jwn6g6crryvq9pwvhffv6',)
2019-11-16 16:08:57,264 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('oq6riptmjh0jwn6g6crryvq9pwvhffv6', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 08:18:57.262735'); args=('oq6riptmjh0jwn6g6crryvq9pwvhffv6', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 08:18:57.262735')
2019-11-16 16:08:57,431 [Thread-2:196180] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 16:57:35,681 [Dummy-1:201012] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 16:57:35,681 [Dummy-1:201012] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 16:57:35,684 [Dummy-1:201012] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2019-11-16 16:57:35,689 [Dummy-1:201012] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:14:59,890 [Dummy-1:201988] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:14:59,890 [Dummy-1:201988] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:14:59,893 [Dummy-1:201988] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:14:59,898 [Dummy-1:201988] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:15:08,759 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:15:10,014 [Thread-2:202172] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:15:10,044 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:15:10,044 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:15:10,046 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:15:10,047 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ocqs48hwqocr1bsqd5neravabxo37yo3'  LIMIT 1; args=('ocqs48hwqocr1bsqd5neravabxo37yo3',)
2019-11-16 17:15:10,049 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('ocqs48hwqocr1bsqd5neravabxo37yo3', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:25:10.048966'); args=('ocqs48hwqocr1bsqd5neravabxo37yo3', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:25:10.048966')
2019-11-16 17:15:10,236 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 17:15:11,360 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:15:11,361 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:15:11.357040' AND `django_session`.`session_key` = 'ocqs48hwqocr1bsqd5neravabxo37yo3'); args=('2019-11-16 09:15:11.357040', 'ocqs48hwqocr1bsqd5neravabxo37yo3')
2019-11-16 17:15:11,362 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:15:11,395 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:15:11,398 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:15:11.391042' AND `django_session`.`session_key` = 'ocqs48hwqocr1bsqd5neravabxo37yo3'); args=('2019-11-16 09:15:11.391042', 'ocqs48hwqocr1bsqd5neravabxo37yo3')
2019-11-16 17:15:11,411 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:15:11,415 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` INNER JOIN `authorization_user_menu` ON (`apps_app`.`appid` = `authorization_user_menu`.`app_id`) WHERE `authorization_user_menu`.`user_id` = 3; args=(3,)
2019-11-16 17:15:11,416 [Thread-2:202172] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/menu/user HTTP/1.1" 200 278
2019-11-16 17:17:27,068 [Dummy-1:199540] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:17:27,069 [Dummy-1:199540] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:17:27,071 [Dummy-1:199540] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:17:27,076 [Dummy-1:199540] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:18:14,424 [Dummy-1:202060] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:18:14,424 [Dummy-1:202060] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:18:14,427 [Dummy-1:202060] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2019-11-16 17:18:14,431 [Dummy-1:202060] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:18:38,429 [Dummy-1:201932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:18:38,430 [Dummy-1:201932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:18:38,432 [Dummy-1:201932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:18:38,437 [Dummy-1:201932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:19:10,418 [Dummy-1:193656] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:19:10,419 [Dummy-1:193656] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:19:10,421 [Dummy-1:193656] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:19:10,538 [Dummy-1:193656] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.103) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:19:31,632 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:19:49,977 [Thread-2:198764] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:19:49,987 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:19:49,987 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:19:49,989 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:19:49,992 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = '35lzhz6l44eheo4sqstpb8uwxjrugsin'  LIMIT 1; args=('35lzhz6l44eheo4sqstpb8uwxjrugsin',)
2019-11-16 17:19:49,996 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('35lzhz6l44eheo4sqstpb8uwxjrugsin', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:29:49.992977'); args=('35lzhz6l44eheo4sqstpb8uwxjrugsin', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:29:49.992977')
2019-11-16 17:19:50,150 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 17:19:50,703 [Thread-2:198764] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:19:50,710 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:19:50,714 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:19:50,718 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = '1xc92ryulo5ke532186nh8tpxnfs2494'  LIMIT 1; args=('1xc92ryulo5ke532186nh8tpxnfs2494',)
2019-11-16 17:19:50,721 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('1xc92ryulo5ke532186nh8tpxnfs2494', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:29:50.718019'); args=('1xc92ryulo5ke532186nh8tpxnfs2494', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:29:50.718019')
2019-11-16 17:19:50,814 [Thread-2:198764] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 17:21:21,715 [Dummy-1:201428] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:21:21,716 [Dummy-1:201428] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:21:21,723 [Dummy-1:201428] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.007) SHOW FULL TABLES; args=None
2019-11-16 17:21:21,727 [Dummy-1:201428] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:21:24,984 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:21:24,984 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:21:24,997 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.013) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:21:24.978410' AND `django_session`.`session_key` = '1xc92ryulo5ke532186nh8tpxnfs2494'); args=('2019-11-16 09:21:24.978410', '1xc92ryulo5ke532186nh8tpxnfs2494')
2019-11-16 17:21:24,998 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:21:25,047 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:21:25,049 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:21:25.028413' AND `django_session`.`session_key` = '1xc92ryulo5ke532186nh8tpxnfs2494'); args=('2019-11-16 09:21:25.028413', '1xc92ryulo5ke532186nh8tpxnfs2494')
2019-11-16 17:21:25,114 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /service/menu/user
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\apps\views\menu.py", line 53, in get
    logger.info('session content in service/menu/user: ' + request.session.session_key + request.session.items())
TypeError: can only concatenate str (not "dict_items") to str
2019-11-16 17:21:25,116 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "GET /service/menu/user HTTP/1.1" 500 80289
2019-11-16 17:21:27,840 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:21:27,843 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:21:27.836574' AND `django_session`.`session_key` = '1xc92ryulo5ke532186nh8tpxnfs2494'); args=('2019-11-16 09:21:27.836574', '1xc92ryulo5ke532186nh8tpxnfs2494')
2019-11-16 17:21:27,871 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /auth/logout
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 74, in logout
    logger.info('session content in auth/logout: ' + request.session.items())
TypeError: can only concatenate str (not "dict_items") to str
2019-11-16 17:21:27,872 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "GET /auth/logout HTTP/1.1" 500 71094
2019-11-16 17:21:29,912 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:21:29,913 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:21:29.905692' AND `django_session`.`session_key` = '1xc92ryulo5ke532186nh8tpxnfs2494'); args=('2019-11-16 09:21:29.905692', '1xc92ryulo5ke532186nh8tpxnfs2494')
2019-11-16 17:21:29,942 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /auth/logout
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 74, in logout
    logger.info('session content in auth/logout: ' + request.session.items())
TypeError: can only concatenate str (not "dict_items") to str
2019-11-16 17:21:29,943 [Thread-2:196284] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "GET /auth/logout HTTP/1.1" 500 71094
2019-11-16 17:24:20,033 [Dummy-1:200732] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:24:20,034 [Dummy-1:200732] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:24:20,036 [Dummy-1:200732] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:24:20,040 [Dummy-1:200732] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:27:26,374 [Dummy-1:203088] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:27:26,375 [Dummy-1:203088] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:27:26,377 [Dummy-1:203088] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:27:26,381 [Dummy-1:203088] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:28:12,920 [Thread-2:202792] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:28:14,361 [Thread-2:202792] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /auth/authorize
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 19, in authorize
    return __authorize_by_code(request)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 22, in __authorize_by_code
    logger.info('session content in auth/authorize01: '+ request.session.session_key)
TypeError: can only concatenate str (not "NoneType") to str
2019-11-16 17:28:14,363 [Thread-2:202792] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "POST /auth/authorize HTTP/1.1" 500 73669
2019-11-16 17:31:22,185 [Dummy-1:201248] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:31:22,185 [Dummy-1:201248] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:31:22,188 [Dummy-1:201248] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2019-11-16 17:31:22,193 [Dummy-1:201248] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:32:36,971 [Dummy-1:201880] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:32:36,971 [Dummy-1:201880] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:32:36,974 [Dummy-1:201880] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2019-11-16 17:32:36,979 [Dummy-1:201880] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:32:40,794 [Thread-2:202600] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:32:40,840 [Thread-2:202600] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /auth/authorize
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 19, in authorize
    return __authorize_by_code(request)
  File "G:\pythonProject\Django\myWX_l_ningmo\authorization\views.py", line 50, in __authorize_by_code
    logger.info('session content in auth/authorize: ' + request.session.session_key)
TypeError: can only concatenate str (not "NoneType") to str
2019-11-16 17:32:40,842 [Thread-2:202600] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "POST /auth/authorize HTTP/1.1" 500 75380
2019-11-16 17:33:40,172 [Dummy-1:197932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:33:40,172 [Dummy-1:197932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:33:40,175 [Dummy-1:197932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2019-11-16 17:33:40,180 [Dummy-1:197932] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:33:42,916 [Thread-2:187032] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:33:42,920 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:33:42,921 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:33:42,921 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:33:42,924 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'g2mzkoaz2jc83oxr366uvhu06j7i6ron'  LIMIT 1; args=('g2mzkoaz2jc83oxr366uvhu06j7i6ron',)
2019-11-16 17:33:42,926 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('g2mzkoaz2jc83oxr366uvhu06j7i6ron', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:43:42.924618'); args=('g2mzkoaz2jc83oxr366uvhu06j7i6ron', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:43:42.924618')
2019-11-16 17:33:43,075 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 17:33:50,758 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:33:50,759 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:33:50.754066' AND `django_session`.`session_key` = 'g2mzkoaz2jc83oxr366uvhu06j7i6ron'); args=('2019-11-16 09:33:50.754066', 'g2mzkoaz2jc83oxr366uvhu06j7i6ron')
2019-11-16 17:33:50,760 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:33:50,795 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:33:50,796 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:33:50.789068' AND `django_session`.`session_key` = 'g2mzkoaz2jc83oxr366uvhu06j7i6ron'); args=('2019-11-16 09:33:50.789068', 'g2mzkoaz2jc83oxr366uvhu06j7i6ron')
2019-11-16 17:33:50,797 [Thread-2:187032] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\menu.py:get:53] [INFO]- session content in service/menu/user: g2mzkoaz2jc83oxr366uvhu06j7i6ron
2019-11-16 17:33:50,798 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:33:50,800 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` INNER JOIN `authorization_user_menu` ON (`apps_app`.`appid` = `authorization_user_menu`.`app_id`) WHERE `authorization_user_menu`.`user_id` = 3; args=(3,)
2019-11-16 17:33:50,801 [Thread-2:187032] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/menu/user HTTP/1.1" 200 278
2019-11-16 17:34:14,776 [Thread-3:203560] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py:post:75] [INFO]- image file from weixin, key is : test
2019-11-16 17:34:14,825 [Thread-3:203560] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\utils\log.py:log_response:222] [ERROR]- Internal Server Error: /service/image
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py", line 76, in post
    logger.info('image file from weixin, uploaded_file is : ' + uploaded_file)
TypeError: can only concatenate str (not "InMemoryUploadedFile") to str
2019-11-16 17:34:14,827 [Thread-3:203560] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [ERROR]- "POST /service/image HTTP/1.1" 500 79851
2019-11-16 17:35:03,133 [Dummy-1:200864] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:35:03,133 [Dummy-1:200864] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:35:03,139 [Dummy-1:200864] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.006) SHOW FULL TABLES; args=None
2019-11-16 17:35:03,143 [Dummy-1:200864] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-11-16 17:35:15,639 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:35:17,136 [Thread-2:203496] [G:\pythonProject\Django\myWX_l_ningmo\utils\wx\code2session.py:code2session:20] [INFO]- result from weixinServer : 
2019-11-16 17:35:17,141 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-11-16 17:35:17,142 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:35:17,142 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:35:17,144 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'  LIMIT 1; args=('mnq6od16q9lmoanbfv6iohte2yy8mw3m',)
2019-11-16 17:35:17,145 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('mnq6od16q9lmoanbfv6iohte2yy8mw3m', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:45:17.144007'); args=('mnq6od16q9lmoanbfv6iohte2yy8mw3m', 'ODhhMWVhMGRjMzBmNGIyM2UzMGZhM2M1NDZkMmVkZjhmYTgxZjczMTp7Im9wZW5faWQiOiJvWDlEWDVTb3otRFdrdWVsc1ZMSnREZFNZd0ZjIiwiaXNfYXV0aG9yaXplZCI6dHJ1ZX0=', '2019-11-16 09:45:17.144007')
2019-11-16 17:35:17,290 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /auth/authorize HTTP/1.1" 200 61
2019-11-16 17:35:20,004 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:35:20,005 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:35:19.996171' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:35:19.996171', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:35:20,006 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:35:20,081 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:35:20,083 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:35:20.078175' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:35:20.078175', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:35:20,083 [Thread-2:203496] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\menu.py:get:53] [INFO]- session content in service/menu/user: mnq6od16q9lmoanbfv6iohte2yy8mw3m
2019-11-16 17:35:20,086 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:35:20,092 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.005) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` INNER JOIN `authorization_user_menu` ON (`apps_app`.`appid` = `authorization_user_menu`.`app_id`) WHERE `authorization_user_menu`.`user_id` = 3; args=(3,)
2019-11-16 17:35:20,093 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/menu/user HTTP/1.1" 200 278
2019-11-16 17:35:37,494 [Thread-3:204116] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py:post:75] [INFO]- image file from weixin, key is : test
2019-11-16 17:35:37,495 [Thread-3:204116] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py:post:80] [INFO]- image file from weixin, md5 is : e38c53f156505ff1eca61a9b00c8302a
2019-11-16 17:35:37,522 [Thread-3:204116] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /service/image HTTP/1.1" 200 111
2019-11-16 17:35:37,672 [Thread-4:204124] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/image?md5=e38c53f156505ff1eca61a9b00c8302a HTTP/1.1" 200 174195
2019-11-16 17:35:45,020 [Thread-5:204532] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py:post:75] [INFO]- image file from weixin, key is : test
2019-11-16 17:35:45,020 [Thread-5:204532] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\image.py:post:80] [INFO]- image file from weixin, md5 is : 24bc3cad104d3fc80fdb70ed1e1cb664
2019-11-16 17:35:45,041 [Thread-5:204532] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /service/image HTTP/1.1" 200 111
2019-11-16 17:35:45,141 [Thread-6:204540] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/image?md5=24bc3cad104d3fc80fdb70ed1e1cb664 HTTP/1.1" 200 105452
2019-11-16 17:35:52,008 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "DELETE /service/image?md5=e38c53f156505ff1eca61a9b00c8302a HTTP/1.1" 200 48
2019-11-16 17:36:06,651 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:36:06,651 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:36:06.639838' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:36:06.639838', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:36:06,652 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:36:06,867 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:36:06,867 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app`; args=()
2019-11-16 17:36:06,868 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/menu/list HTTP/1.1" 200 1137
2019-11-16 17:36:15,166 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:36:15,167 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:36:15.163326' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:36:15.163326', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:36:15,167 [Thread-2:203496] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\menu.py:post:70] [INFO]- session content in service/menu/user: mnq6od16q9lmoanbfv6iohte2yy8mw3m
2019-11-16 17:36:15,169 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:36:15,172 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` WHERE `apps_app`.`appid` = '549eaaf72cb23716e2b1313acfaed23c'; args=('549eaaf72cb23716e2b1313acfaed23c',)
2019-11-16 17:36:15,173 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` WHERE `apps_app`.`appid` = '7b27422f98f13eb2610f1996ec757be7'; args=('7b27422f98f13eb2610f1996ec757be7',)
2019-11-16 17:36:15,176 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `apps_app`.`appid` FROM `apps_app` INNER JOIN `authorization_user_menu` ON (`apps_app`.`appid` = `authorization_user_menu`.`app_id`) WHERE `authorization_user_menu`.`user_id` = 3; args=(3,)
2019-11-16 17:36:15,177 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `authorization_user_menu`.`app_id` FROM `authorization_user_menu` WHERE (`authorization_user_menu`.`app_id` IN ('7b27422f98f13eb2610f1996ec757be7') AND `authorization_user_menu`.`user_id` = 3); args=('7b27422f98f13eb2610f1996ec757be7', 3)
2019-11-16 17:36:15,267 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.089) INSERT INTO `authorization_user_menu` (`user_id`, `app_id`) VALUES (3, '7b27422f98f13eb2610f1996ec757be7'); args=(3, '7b27422f98f13eb2610f1996ec757be7')
2019-11-16 17:36:15,364 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.035) UPDATE `authorization_user` SET `open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc', `nickname` = '此间' WHERE `authorization_user`.`id` = 3; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc', '此间', 3)
2019-11-16 17:36:15,365 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "POST /service/menu/user HTTP/1.1" 200 40
2019-11-16 17:36:21,665 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:36:21,665 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:36:21.661698' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:36:21.661698', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:36:21,666 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /auth/status HTTP/1.1" 200 70
2019-11-16 17:36:21,685 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-11-16 17:36:21,687 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-11-16 09:36:21.682699' AND `django_session`.`session_key` = 'mnq6od16q9lmoanbfv6iohte2yy8mw3m'); args=('2019-11-16 09:36:21.682699', 'mnq6od16q9lmoanbfv6iohte2yy8mw3m')
2019-11-16 17:36:21,687 [Thread-2:203496] [G:\pythonProject\Django\myWX_l_ningmo\apps\views\menu.py:get:53] [INFO]- session content in service/menu/user: mnq6od16q9lmoanbfv6iohte2yy8mw3m
2019-11-16 17:36:21,688 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.000) SELECT `authorization_user`.`id`, `authorization_user`.`open_id`, `authorization_user`.`nickname` FROM `authorization_user` WHERE `authorization_user`.`open_id` = 'oX9DX5Soz-DWkuelsVLJtDdSYwFc'; args=('oX9DX5Soz-DWkuelsVLJtDdSYwFc',)
2019-11-16 17:36:21,692 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\db\backends\utils.py:execute:109] [DEBUG]- (0.003) SELECT `apps_app`.`appid`, `apps_app`.`category`, `apps_app`.`application`, `apps_app`.`name`, `apps_app`.`publish_date`, `apps_app`.`url`, `apps_app`.`desc` FROM `apps_app` INNER JOIN `authorization_user_menu` ON (`apps_app`.`appid` = `authorization_user_menu`.`app_id`) WHERE `authorization_user_menu`.`user_id` = 3; args=(3,)
2019-11-16 17:36:21,693 [Thread-2:203496] [C:\ProgramData\Anaconda3\envs\myP38\lib\site-packages\django\core\servers\basehttp.py:log_message:154] [INFO]- "GET /service/menu/user HTTP/1.1" 200 480
